src/routes/common/models.py
from datetime import datetime

from ... import db


class VisitCounter(db.Model):
    __tablename__ = "RouteVisits"

    id = db.Column(db.Integer, primary_key=True)
    year = db.Column(db.Integer, nullable=False)   # ISO year
    week = db.Column(db.Integer, nullable=False)   # ISO week (1–53)
    count = db.Column(db.Integer, default=0)
    route = db.Column(db.String, nullable=True, default="N/A")

    __table_args__ = (db.UniqueConstraint('year', 'week', name='_year_week_uc'),)


# def count_visit(route):
    
#     now = datetime.now()
#     iso_year, iso_week, _ = now.isocalendar()
#     counter = VisitCounter.query.filter_by(year=iso_year, week=iso_week, route=route).first()

#     if not counter:
#         counter = VisitCounter(year=iso_year, week=iso_week, route=route, count=1)
#         db.session.add(counter)
#     else:
#         counter.count += 1
    
#     db.session.commit()

from functools import wraps

def count_visit(route: str):
    def decorator(f):
        @wraps(f)
        def wrapped(*args, **kwargs):
            now = datetime.now()
            iso_year, iso_week, _ = now.isocalendar()

            counter = VisitCounter.query.filter_by(
                year=iso_year, week=iso_week, route=route
            ).first()

            if not counter:
                counter = VisitCounter(year=iso_year, week=iso_week, route=route, count=1)
                db.session.add(counter)
            else:
                counter.count += 1

            db.session.commit()
            return f(*args, **kwargs)
        return wrapped
    return decorator

src/routes/user/models.py
from enum import Enum
from datetime import datetime
from flask_login import UserMixin

from ... import db, bcrypt

class User(UserMixin, db.Model):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=True)
    email = db.Column(db.String, unique=True, nullable=False)
    password = db.Column(db.String, nullable=False)
    created_on = db.Column(db.DateTime, nullable=False)
    is_admin = db.Column(db.Boolean, nullable=False, default=False)
    access_code_id = db.Column(db.Integer, db.ForeignKey("codes.id"), nullable=True)
    community = db.Column(db.String, nullable=False)

    def __init__(self, email, password, community, name=None, is_admin=False):
        self.email = email
        self.password = bcrypt.generate_password_hash(password)
        self.created_on = datetime.now()
        self.name = name
        self.is_admin = is_admin
        self.community = community



    def __repr__(self):
        return f"<email {self.email}>"

class AccessCodeTypes(Enum):
    UKN = 0
    BETA = 1

from secrets import choice
from string import ascii_uppercase, digits
def generate_access_code(length=15):
    alphabet = ascii_uppercase + digits
    return "".join(choice(alphabet) for _ in range(length))

class AccessCode(db.Model):
    __tablename__ = "codes"

    id = db.Column(db.Integer, primary_key=True)
    ctype = db.Column(db.Enum(AccessCodeTypes), nullable=False, default=AccessCodeTypes.UKN)
    code = db.Column(db.String(15), nullable=False)
    created_on = db.Column(db.DateTime, nullable=False)
    created_for = db.Column(db.String, nullable=True)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=True)
    claimed = db.Column(db.Boolean, nullable=False, default=False)
    claimed_on = db.Column(db.DateTime, nullable=True)

    def __init__(self, ctype, created_for=None):
        self.ctype = ctype
        self.created_for = created_for
        self.created_on = datetime.now()
        self.code = generate_access_code()

    def __repr__(self):
        return f"<id {self.id}, code {self.code}>"


        

src/routes/user/forms.py
from flask_wtf import FlaskForm
from wtforms import EmailField, PasswordField, StringField, SelectField, BooleanField
from wtforms.validators import DataRequired, Email, EqualTo, Length
from flask_babel import gettext, lazy_gettext
from sqlalchemy import func

from .models import User, AccessCode, AccessCodeTypes

pw_fieldname = lazy_gettext("Password")
class RegisterForm(FlaskForm):
    email = EmailField(
        lazy_gettext("Email"), validators=[DataRequired(), Email(message=None), Length(min=4, max=40)]
    )
    password = PasswordField(
        pw_fieldname, validators=[DataRequired(), Length(min=6, max=30)]
    )
    confirm = PasswordField(
        lazy_gettext("Repeat Password"),
        validators=[
            DataRequired(),
            EqualTo('password', message=lazy_gettext("Password must match")),
        ],
    )
    terms = BooleanField(lazy_gettext("Terms"), validators=[DataRequired()])
    beta_code = StringField(lazy_gettext("Beta code"), validators=[DataRequired()])
    username = StringField(lazy_gettext("Username"), validators=[DataRequired()])
    community = SelectField(lazy_gettext("Community"), validators=[DataRequired()],
                            choices=
                            [
                                ("Cañari", "Cañari"),
                                ("Caranqui", "Caranqui"),
                                ("Cayambi", "Cayambi"),
                                ("Chibuleo", "Chibuleo"),
                                ("Guaranga", "Guaranga"),
                                ("Natabuela", "Natabuela"),
                                ("Otavalo", "Otavalo"),
                                ("Panzaleo", "Panzaleo"),
                                ("Puruhá", "Puruhá"),
                                ("Quisapincha", "Quisapincha"),
                                ("Salasaca", "Salasaca"),
                                ("Saraguro", "Saraguro"),
                                ("Tomabela", "Tomabela"),
                                ("Quichuas del Napo", "Quichuas del Napo"),
                                ("Quichuas de Pastaza", "Quichuas de Pastaza")
                            ]
                            )

    def validate(self, extra_validators=None):
        initial_validation = super(RegisterForm, self).validate()
        result = True
        if not initial_validation:
            result = False
        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append(lazy_gettext("Email has already been registered"))
            result = False
        if self.password.data != self.confirm.data:
            self.password.errors.append(lazy_gettext("Passwords must match"))
            result = False
        if not self.terms.data:
            self.terms.errors.append(lazy_gettext("You need to agree to our terms and conditions"))
            result = False
        acode: AccessCode = AccessCode.query.filter_by(code=self.beta_code.data.upper()).first()
        if not acode:
            self.beta_code.errors.append(lazy_gettext("Invalid code, please check spelling"))
            result = False
        else:
            if acode.claimed:
                self.beta_code.errors.append(lazy_gettext("Code has already been claimed"))
                result = False
            if acode.ctype != AccessCodeTypes.BETA:
                self.beta_code.errors.append(lazy_gettext("Wrong type of code"))
                result = False
        return result

class LoginForm(FlaskForm):
    email = EmailField(lazy_gettext("Email"), validators=[DataRequired(), Email()])
    password = PasswordField(lazy_gettext("Password"), validators=[DataRequired()])

src/__init__.py
from flask import Flask
from decouple import config
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy

from .extensions import babel, get_locale

app = Flask(__name__)
app.config.from_object(config("APP_SETTINGS"))

db = SQLAlchemy(app)
bcrypt = Bcrypt(app)
login_manager = LoginManager()
login_manager.init_app(app) 
login_manager.login_view = "user_bp.login"
login_manager.login_message_category = "danger"

babel.init_app(app, locale_selector=get_locale)
@app.context_processor
def inject_get_locale():
    return dict(get_locale=get_locale)

app.config['TEMPLATES_AUTO_RELOAD'] = True

from .routes.common import views
app.register_blueprint(views.bp)

from .routes.legal.views import bp as legal_bp
app.register_blueprint(legal_bp)

from .routes.user.views import bp as user_bp
app.register_blueprint(user_bp)

from .routes.user.models import User

@login_manager.user_loader
def load_user(user_id):
    return User.query.filter(User.id == int(user_id)).first()



with app.app_context():

    from .routes.user import models
    from .routes.common import models

    if app.config.get("TESTING") or app.config.get("DEBUG") or app.config.get("DEVELOPMENT"):
        db.create_all() 

@app.cli.command("drop-db")
def drop_db():
    """Drop all DB tables."""
    confirm = input("Drop all tables? Type 'yes' to confirm: ")
    if confirm == "yes":
        with app.app_context():
            db.drop_all()
        print("Dropped")
    else:
        print("Aborted")

import click

@app.cli.command("create-beta")
@click.option("--created-for", default=None, help="Optional description of who this code is for")
def create_one_code(created_for):
    from .routes.user.models import AccessCode, AccessCodeTypes
    

    while True:
        if created_for:
            code = AccessCode(
                ctype=AccessCodeTypes.BETA,
                created_for=created_for
            )
        else:
            code = AccessCode(
                ctype=AccessCodeTypes.BETA,
            )
        code_str = code.code
        existing = AccessCode.query.filter_by(code=code_str).first()
        if not existing:
            break

    db.session.add(code)
    db.session.commit()
    click.echo(f"Generated BETA access code: {code.code}")

src/routes/common/views.py
from flask import (Blueprint, render_template, request, session, url_for, make_response)

bp = Blueprint("index_bp", __name__)

from .models import count_visit

@bp.route("/")
@count_visit("/")
def index():
    return render_template("index.html")

@bp.route("/about")
def about():
     return render_template("about.html")

@bp.route("/roadmap")
def roadmap():
     return render_template("roadmap.html")

@bp.route("/contribute")
def contribute():
     return render_template("contribute.html")

src/routes/legal/views.py
from flask import (Blueprint, render_template, request, session, url_for, make_response, send_from_directory, Response)

bp = Blueprint("legal_bp", __name__)

@bp.route("/terms")
def terms():
     return render_template("legal/terms.html")

@bp.route("/imprint")
def imprint():
     return render_template("legal/imprint.html")




@bp.route("/robots.txt")
def robots():
     robots =  """
     # robots.txt file for Open Kichwa / Kichwa Paskana
     # Created with love from Germany <3
     
     User-agent: *
     Disallow: /profile
     Disallow: /terms
     Disallow: /signup
     Disallow: /login
     Disallow: /logout
"""  
     return Response(robots, mimetype="text/plain")


# TODO:
# Privacy, cookie banner, imprint

src/routes/user/views.py
from flask import (Blueprint, render_template, request, session, url_for, make_response, flash, redirect)
from flask_login import login_required, login_user, current_user, logout_user
from flask_babel import gettext
from datetime import datetime

from .forms import RegisterForm, LoginForm
from .models import User, AccessCode

from ... import db, bcrypt, babel
from ...routes.common.models import count_visit

bp = Blueprint("user_bp", __name__)

@bp.route("/logout")
@login_required
def logout():
    logout_user()
    flash("You were logged out.", "success")
    return redirect(url_for("user_bp.login"))


@bp.route("/login", methods=["GET", "POST"])
def login():
     if request.method == "POST":
          if current_user.is_authenticated:
               flash(gettext("You are already logged in"), "info")
               return redirect(url_for("index_bp.index"))
          
          form = LoginForm(request.form)
          if form.validate_on_submit():
               user = User.query.filter_by(email=form.email.data).first()
               if user and bcrypt.check_password_hash(user.password, request.form["password"]):
                    login_user(user)
                    return redirect(url_for("index_bp.index"))
               else:
                    flash(gettext("Invalid email and/or password"), "danger")
                    return render_template("user/login.html", form=form)
          return render_template("user/login.html", form=form)
     else:
          form = LoginForm()
          return render_template("user/login.html", form=form)

@count_visit("/signup")
@bp.route("/signup", methods=["GET", "POST"])
def signup():
     if request.method == "POST":
          if current_user.is_authenticated:
               flash(gettext("You are already registered"), "info")
               return redirect(url_for("index_bp.index"))
          form = RegisterForm(request.form)
          if form.validate_on_submit():
               user = User(email=form.email.data, password=form.password.data, community=form.community.data, name=form.username.data)
               db.session.add(user)
               db.session.flush()

               code: AccessCode = AccessCode.query.filter_by(code=form.beta_code.data).first()
               user.access_code_id = code.id
               code.claimed = True
               code.claimed_on = datetime.now()
               code.user_id = user.id        
               db.session.commit()

               login_user(user)
               flash(gettext("You have been registered!"), "success")

               return redirect(url_for("user_bp.profile"))
          return render_template("user/signup.html", form=form)
     else:     
          form = RegisterForm()
          return render_template("user/signup.html", form=form)

     
@bp.route("/profile")
@login_required
def profile():
     return "you are logged in!!!!!"

src/user/views.py
from flask import (Blueprint, render_template, request, session, url_for, make_response, flash, redirect)
from flask_login import login_required, login_user, current_user, logout_user
from flask_babel import gettext
from datetime import datetime

from .forms import RegisterForm, LoginForm
from .models import User, AccessCode

from .. import db, bcrypt, babel

bp = Blueprint("user_bp", __name__)

@bp.route("/logout")
@login_required
def logout():
    logout_user()
    flash("You were logged out.", "success")
    return redirect(url_for("user_bp.login"))


@bp.route("/login", methods=["GET", "POST"])
def login():
     if request.method == "POST":
          if current_user.is_authenticated:
               flash(gettext("You are already logged in"), "info")
               return redirect(url_for("index_bp.index"))
          
          form = LoginForm(request.form)
          if form.validate_on_submit():
               user = User.query.filter_by(email=form.email.data).first()
               if user and bcrypt.check_password_hash(user.password, request.form["password"]):
                    login_user(user)
                    return redirect(url_for("index_bp.index"))
               else:
                    flash(gettext("Invalid email and/or password"), "danger")
                    return render_template("user/login.html", form=form)
          return render_template("user/login.html", form=form)
     else:
          form = LoginForm()
          return render_template("user/login.html", form=form)

@bp.route("/signup", methods=["GET", "POST"])
def signup():
     if request.method == "POST":
          if current_user.is_authenticated:
               flash(gettext("You are already registered"), "info")
               return redirect(url_for("index_bp.index"))
          form = RegisterForm(request.form)
          if form.validate_on_submit():
               user = User(email=form.email.data, password=form.password.data, community=form.community.data, name=form.username.data)
               db.session.add(user)
               db.session.flush()

               code: AccessCode = AccessCode.query.filter_by(code=form.beta_code.data).first()
               user.access_code_id = code.id
               code.claimed = True
               code.claimed_on = datetime.now()
               code.user_id = user.id        
               db.session.commit()

               login_user(user)
               flash(gettext("You have been registered!"), "success")

               return redirect(url_for("user_bp.profile"))
          return render_template("user/signup.html", form=form)
     else:     
          form = RegisterForm()
          return render_template("user/signup.html", form=form)

     
@bp.route("/profile")
@login_required
def profile():
     return "you are logged in!!!!!"

src/templates/common/base.html
<!doctype html>
<html>
<head>
    <meta charset="UTF-8"> 
    <title>{% block title %}{% endblock %} Open Kichwa</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="preload" as="style" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
    <link href="{{ url_for('static', filename='css/colors.css') }}" rel="preload" as="style">
    <link href="{{ url_for('static', filename='css/navbar.css') }}" rel="preload" as="style">
    <link rel="preload" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" as="script" crossorigin="anonymous">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
    <link href="{{ url_for('static', filename='css/colors.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/navbar.css') }}" rel="stylesheet">
    {% block header %}{% endblock %}
   
</head>

<body>
    
    <div class="d-flex justify-content-between align-items-center">
        <div>
            <a href="{{ url_for('index_bp.index') }}">
                <img class="responsive-logo"
                src="{{ url_for('static', filename='images/text over logo no bg.png') }}"
                alt="Logo">
            </a>
        </div>

        {% if get_locale() == 'es' %}
        <div class="text-muted small fst-italic me-2">
            *Esta traducción fue generada automáticamente
        </div>
        {% endif %}
    </div>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark px-3">
        <div class="container-fluid">

            <a class="navbar-brand" href="#"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link {% if request.endpoint == 'about' %}active{% endif %}" href="{{ url_for('index_bp.about') }}">{{ gettext("About") }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.endpoint == 'contribute' %}active{% endif %}" href="{{ url_for('index_bp.contribute') }}">{{ gettext("contribute") }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.endpoint == 'roadmap' %}active{% endif %}" href="{{ url_for('index_bp.roadmap') }}">{{ gettext("roadmap") }}</a>
                    </li>
                   
                </ul>
                <ul class="navbar-nav ms-auto mt-3 mt-lg-0">
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="btn btn-sm btn-outline-danger ms-lg-2 w-100" 
                        href="{{ url_for('user_bp.logout') }}">{{ gettext("Logout") }}</a>
                    </li>
                    {% else %}
                    <li class="nav-item px-3">
                        <a class="btn btn-sm btn-primary ms-lg-2 w-100" 
                        href="{{ url_for('user_bp.login') }}">{{ gettext("Login") }}</a>
                    </li>
                    <li class="nav-item mt-2 mt-lg-0">
                        <a class="btn btn-sm btn-secondary ms-lg-2 w-100" 
                        href="{{ url_for('user_bp.signup') }}">{{ gettext("Sign up") }}</a>
                    </li>
                    {% endif %}
                </ul>

                <!-- MOBILE Language Selector -->
                <div class="lang-selector d-lg-none w-100 mt-3 d-flex justify-content-end">
                    <div class="dropdown">
                    <button class="btn btn-outline-light dropdown-toggle" type="button" data-bs-toggle="dropdown">
                        {{ 'EN' if get_locale() == 'en' else 'ES' }}
                    </button>
                    <ul class="dropdown-menu dropdown-menu-end">
                        <li><a class="dropdown-item" href="{{ url_for(request.endpoint, lang='en', **request.view_args) }}">EN</a></li>
                        <li><a class="dropdown-item" href="{{ url_for(request.endpoint, lang='es', **request.view_args) }}">ES</a></li>
                    </ul>
                    </div>
                </div>

                <!-- DESKTOP Language Selector -->
                <div class="dropdown d-none d-lg-block px-3">
                    <button class="btn btn-outline-light dropdown-toggle" type="button" data-bs-toggle="dropdown">
                        {{ 'ES' if get_locale() == 'es' else 'EN' }}
                    </button>
                    <ul class="dropdown-menu dropdown-menu-end">
                        <li><a class="dropdown-item" href="{{ url_for(request.endpoint, lang='en', **request.view_args) }}">EN</a></li>
                        <li><a class="dropdown-item" href="{{ url_for(request.endpoint, lang='es', **request.view_args) }}">ES</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      <div class="row my-3 mx-3">
        <div class="col-md-4"></div>
        <div class="col-md-4">
          {% for category, message in messages %}
          <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
           {{message}}
           <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
          {% endfor %}
        </div>
        <div class="col-md-4"></div>
      </div>
      {% endif %}
    {% endwith %}


    <section class="content">
        <div class="container my-4">
            {% block content %}{% endblock %}
        </div>
        
    </section>

    <footer class="footer bg-dark text-light py-2 mt-auto fixed-bottom">
  <div class="container text-center">
    <span class="mx-2">
      <a href="{{ url_for('legal_bp.terms') }}" class="text-light text-decoration-none">
        {{ gettext("Terms") }}
      </a>
    </span>
    |
    <span class="mx-2">
      <a href="{{ url_for('legal_bp.imprint') }}" class="text-light text-decoration-none">
        {{ gettext("Imprint") }}
      </a>
    </span>
    |
    <span class="mx-2">
      <a href="mailto:open.kichwa@proton.me" class="text-light text-decoration-none">
        {{ gettext("Contact us") }}
      </a>
    </span>
    |
    <span class="mx-2">
      <a href="https://www.instagram.com/openkichwa/" target="_blank" class="text-light text-decoration-none">
        {{ gettext("Instagram") }}
      </a>
    </span>
    |
    <span class="mx-2">
      Open Kichwa © 2025
    </span>
  </div>
</footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" defer></script>
</body>
</html>